Models/ErrorViewModel.cs
using System;

namespace AspNetCoreMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Filme.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AspNetCoreMVC.Models
{
    public class Filme
    {
        [Key]
        public int Id {get; set;}

        [Required(ErrorMessage = "O campo titulo é obrigatorio!")]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "O Titulo precisa ter entre 3 e 60 caracteres!")]
        public string Titulo {get; set;}

        [DataType(DataType.DateTime, ErrorMessage = "Data em formato incorreto!")]
        [Required(ErrorMessage = "O campo Data de Lançamento é obrigatorio!")]
        [Display(Name= "Data de Lançamento")]
        public DateTime DataLancamento {get; set;}

        [RegularExpression(@"^[A-Z]+[a-zA-Z\u00C0-\u00FF""'\w-]*$", ErrorMessage = "Genero em formato inválido")]
        [Required(ErrorMessage = "O campo Genero é obrigatório!")]
        [StringLength(30, ErrorMessage = "Máximo de 30 caracteres")]
        public string Genero {get; set;}

        [Range(1,1000, ErrorMessage = "Valor 1 a 1000")]
        [Required(ErrorMessage = "Preencha o campo valor")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Valor {get; set;}

        [Required(ErrorMessage = "Preencha o campo Avaliação")]
        [Display(Name = "Avaliação")]
        [RegularExpression(@"^[0-5]*$", ErrorMessage = "Somente Números")]
        public int Avaliacao {get; set;}
    }
}

Controllers/FilmesController.cs
using AspNetCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace aspnetcoremvc.Controllers
{
    public class FilmesController : Controller
    {   
        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(Filme filme)
        {
            if (ModelState.IsValid)
            {
                //
            }
            return View(filme);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AspNetCoreMVC.Models;

namespace AspNetCoreMVC.Controllers
{
    //[Route("gestao")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [Route("")]
        public IActionResult Index()
        {
            var filme = new Filme
            {
                Titulo = "Oi",
                DataLancamento = DateTime.Now,
                Genero = null,
                Avaliacao = 10,
                Valor = 2000
            };
            return RedirectToAction("Privacy", filme);
            //return View();
        }
        [Route("Privacidade")]
        public IActionResult Privacy(Filme filme)
        {
            if (ModelState.IsValid) 
            {

            }

            foreach (var error in ModelState.Values.SelectMany(m => m.Errors))
            {
                Console.WriteLine(error.ErrorMessage);
            }

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("pagina-nao-localizada")]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Filmes/Adicionar.cshtml
@model AspNetCoreMVC.Models.Filme

@{
    ViewData["Title"] = "Adicionar novo Filme";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Adicionar">
            <div asp-validation-summary="All" class="Text-danger">

            </div>

            <div class="form-group">
                <label asp-for="Titulo" class="form-label"></label>
                <input asp-for="Titulo" class="form-control"/>
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataLancamento" class="form-label"></label>
                <input asp-for="DataLancamento" class="form-control"/>
                <span asp-validation-for="DataLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="form-label"></label>
                <input asp-for="Genero" class="form-control"/>
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="form-label"></label>
                <input asp-for="Valor" class="form-control"/>
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avaliacao" class="form-label"></label>
                <input asp-for="Avaliacao" class="form-control"/>
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/Components/Carrinho/Default.cshtml
@model int 

<span class="fa fa-shopping-cart fa-2x">@Model</span>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCoreMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmes" asp-action="Adicionar">Filmes</a>
                        </li>
                    </ul>
                </div>
                <vc:Carrinho></vc:Carrinho>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AspNetCoreMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>